/**

丰收贷
商赢宝
农联宝
保商赢
抵好贷
聚好贷（专案）
保商赢(存量)

*/

-- 放款笔数 292 、放款金额 1849.47 万元 , 向292名客户

SELECT COUNT(1) NBR, SUM(L.DIS_AMT)/10000  AMT, COUNT(DISTINCT L.PARTNER_NO) P_NBR
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '小微一般贷款'
AND L.LOAN_TYP ='农联宝'

;

-- 结清情况 :56户 涉及本金320万, 实现利息收入27万元。
SELECT COUNT(1) NBR, SUM(L.DIS_AMT)/10000  AMT, COUNT(DISTINCT L.PARTNER_NO) P_NBR ,SUM(L.PINT_AMT)/10000 PINT_AMT
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '小微一般贷款'
AND L.LOAN_TYP ='农联宝'
AND L.SETL_FLG = 'Y'

;

-- 未结清 情况，笔数、户数、本金余额，累计已收利息, 产品平均利率
SELECT COUNT(1) NBR, SUM(L.DIS_AMT)/10000  AMT, COUNT(DISTINCT L.PARTNER_NO) P_NBR ,SUM(L.PINT_AMT)/10000 PINT_AMT ,AVG(L.EXCU_RATE) EXCU_RATE
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '小微一般贷款'
AND L.LOAN_TYP ='农联宝'
AND L.SETL_FLG = 'N'
;

-- 未结清 逾期情况
SELECT L.LOAN_CLASS, COUNT(1) NBR, SUM(L.DIS_AMT)/10000  AMT, COUNT(DISTINCT L.PARTNER_NO) P_NBR ,SUM(L.PINT_AMT)/10000 PINT_AMT ,AVG(L.EXCU_RATE) EXCU_RATE
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '小微一般贷款'
AND L.LOAN_TYP ='农联宝'
AND L.SETL_FLG = 'N'
GROUP BY L.LOAN_CLASS
;

-- 客户贷款频次分布

SELECT
 L.PARTNER_NO,
 COUNT(DISTINCT L.LOAN_NO) NBR
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '小微一般贷款'
AND L.LOAN_TYP ='农联宝'
GROUP BY PARTNER_NO
ORDER BY 2 DESC
;

SELECT L.*
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '小微一般贷款'
AND L.LOAN_TYP ='农联宝'
AND L.SETL_FLG = 'N'

;
