SELECT C.*, D.* FROM cs01 C,CHINA_ID D
WHERE 1=1
AND LEFT(C.IDF_NUM,4) = D.AREA_CODE
AND EXISTS(SELECT 1 FROM loan_info L WHERE L.PARTNER_NO = C.CUST_ID AND L.PRODUCT_TYP = '小微一般贷款' AND L.LOAN_TYP ='商赢宝')

;
SELECT *
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '小微一般贷款'
AND L.LOAN_TYP ='商赢宝'
AND L.LOAN_CLASS = '逾期'
AND L.PARTNER_NO LIKE '1%'

;

SELECT LEFT(C.OPEN_ORG_NUM,2) FH, COUNT(DISTINCT C.CUST_ID) CP
FROM cs01 C
WHERE 1=1
AND EXISTS(SELECT 1 FROM loan_info L WHERE L.PARTNER_NO = C.CUST_ID AND L.PRODUCT_TYP = '小微一般贷款' AND L.LOAN_TYP ='商赢宝')
GROUP BY LEFT(C.OPEN_ORG_NUM,2)
ORDER BY 2 DESC

;

-- 客户年份
SELECT LEFT(C.OPEN_DT,4) YF, COUNT(DISTINCT C.CUST_ID) CP
FROM cs01 C
WHERE 1=1
AND EXISTS(SELECT 1 FROM loan_info L WHERE L.PARTNER_NO = C.CUST_ID AND L.PRODUCT_TYP = '小微一般贷款' AND L.LOAN_TYP ='商赢宝')
GROUP BY LEFT(C.OPEN_DT,4)
ORDER BY 1 DESC

;

-- 客户地区
SELECT D.province_name, SUM(D.DIS_AMT)/10000 AMT, COUNT(DISTINCT D.LOAN_NO) CP
FROM T_loan_s01_syb2 D
WHERE 1=1
GROUP BY D.province_name
ORDER BY 3 DESC,2 DESC

;

-- 年龄结构

SELECT 2021 - SUBSTR(C.IDF_NUM,7,4) BIRTH
FROM cs01 C
WHERE 1=1
AND EXISTS(SELECT 1 FROM loan_info L WHERE L.PARTNER_NO = C.CUST_ID AND L.PRODUCT_TYP = '小微一般贷款' AND L.LOAN_TYP ='商赢宝' )
ORDER BY 1 DESC

;

SELECT * FROM loan_due_amt T
WHERE 1=1
AND T.LOAN_TYP = '商赢宝'
AND T.BHDT_BCH_CDE = '03'
AND T.TRD_MON = '2021-05-01'
