/**

丰收贷
商赢宝
商赢宝
保商赢
抵好贷
聚好贷（专案）
保商赢(存量)

*/

-- 1 放款笔数 292 、放款金额 1849.47 万元 , 向292名客户

SELECT COUNT(1) NBR, SUM(L.DIS_AMT)/10000 AMT_SUM, AVG(L.DIS_AMT)/10000  AMT_AVG, COUNT(DISTINCT L.PARTNER_NO) P_NBR, AVG(L.FKQX) FKQX
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
;


SELECT LEFT(l.PARTNER_NO,1) kh,COUNT(1) nbr ,COUNT(DISTINCT l.PARTNER_NO) nbrP ,SUM(L.DIS_AMT)/10000 AMT_SUM, AVG(L.DIS_AMT)/10000  AMT_AVG, AVG(L.FKQX) FKQX
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
GROUP BY LEFT(l.PARTNER_NO,1)
;

-- 2 结清情况 :56户 涉及本金320万, 实现利息收入27万元。
SELECT COUNT(1) NBR, MAX(L.LAST_SETL_DT) LAST_SETL_DT, SUM(L.DIS_AMT)/10000  AMT_SUM, AVG(L.DIS_AMT)/10000  AMT_AVG, COUNT(DISTINCT L.PARTNER_NO) P_NBR ,SUM(L.PINT_AMT)/10000 PINT_AMT, AVG(L.FKQX) FKQX ,AVG(L.YKQX) YKQX
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
AND L.SETL_FLG = 'Y'

;

-- 3 未结清 情况，笔数、户数、本金余额，累计已收利息, 产品平均利率
SELECT COUNT(1) NBR, SUM(L.DIS_AMT)/10000  AMT_SUM, AVG(L.DIS_AMT)/10000  AMT_AVG, COUNT(DISTINCT L.PARTNER_NO) P_NBR ,SUM(L.BASE_AMT)/10000 BASE_AMT ,SUM(L.RES_AMT)/10000 RES_AMT ,SUM(L.PINT_AMT)/10000 PINT_AMT ,AVG(L.EXCU_RATE) EXCU_RATE
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
AND L.SETL_FLG = 'N'

;

-- 4 未结清 逾期情况
SELECT L.LOAN_CLASS, COUNT(1) NBR, SUM(L.DIS_AMT)/10000  AMT_SUM, AVG(L.DIS_AMT)/10000  AMT_AVG, COUNT(DISTINCT L.PARTNER_NO) P_NBR ,SUM(L.PINT_AMT)/10000 PINT_AMT ,AVG(L.EXCU_RATE) EXCU_RATE,SUM(L.BASE_AMT)/10000 BASE_AMT ,SUM(L.RES_AMT)/10000 RES_AMT
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
AND L.SETL_FLG = 'N'
GROUP BY L.LOAN_CLASS

;

-- 5 未结清 还款方式
SELECT L.REPAY_FRQ, COUNT(1) NBR, SUM(L.DIS_AMT)/10000  AMT_SUM, AVG(L.DIS_AMT)/10000  AMT_AVG, COUNT(DISTINCT L.PARTNER_NO) P_NBR ,SUM(L.PINT_AMT)/10000 PINT_AMT ,AVG(L.EXCU_RATE) EXCU_RATE
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
AND L.SETL_FLG = 'N'
GROUP BY L.REPAY_FRQ
;

-- 6 未结清 还款方式2
SELECT L.REP_CATE, COUNT(1) NBR, SUM(L.DIS_AMT)/10000  AMT_SUM, AVG(L.DIS_AMT)/10000  AMT_AVG, COUNT(DISTINCT L.PARTNER_NO) P_NBR ,SUM(L.PINT_AMT)/10000 PINT_AMT ,AVG(L.EXCU_RATE) EXCU_RATE
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
AND L.SETL_FLG = 'N'
GROUP BY L.REP_CATE
;

-- 7 未结清 担保方式
SELECT L.LOAN_SEC_TYP, COUNT(1) NBR, SUM(L.DIS_AMT)/10000  AMT_SUM, AVG(L.DIS_AMT)/10000  AMT_AVG, COUNT(DISTINCT L.PARTNER_NO) P_NBR ,SUM(L.PINT_AMT)/10000 PINT_AMT ,AVG(L.EXCU_RATE) EXCU_RATE
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
AND L.SETL_FLG = 'N'
GROUP BY L.LOAN_SEC_TYP
;






-- 客户贷款频次分布

SELECT
 L.PARTNER_NO,
 COUNT(DISTINCT L.LOAN_NO) NBR
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
GROUP BY PARTNER_NO
ORDER BY 2 DESC
;

SELECT SUM(L.DIS_AMT) DIS_AMT ,SUM(L.BASE_AMT) BASE_AMT
FROM loan_info L
WHERE 1=1
AND L.PRODUCT_TYP = '个人消费类贷款'
AND L.LOAN_TYP LIKE '马上贷%'
AND L.SETL_FLG = 'N'
AND L.LOAN_CLASS = '逾期'
AND L.LAST_SETL_DT < L.LAST_DUE_DT

;

-- 放款节奏
SELECT LEFT(L.ACTV_DT,7) MON ,COUNT(1)
FROM v_loan_s01_nlb L
GROUP BY LEFT(L.ACTV_DT,7)
;


SELECT * FROM v_loan_s01_syb t
where 1=1
and t.REP_CATE ='分期付息一次还本'
and t.FKQX > 400
ORDER BY FKQX desc


;
SELECT LEFT(T.BHDT_BCH_CDE,2) FH, SUM(T.DIS_AMT)/10000  DIS_AMT, SUM(T.BASE_AMT)/10000 BASE_AMT ,COUNT(1) NBR
FROM t_loan_s01_syb2 T
GROUP BY LEFT(T.BHDT_BCH_CDE,2)
ORDER BY 3 DESC

;
SELECT T.BHDT_BCH_CDE FH, SUM(T.DIS_AMT)/10000  DIS_AMT, SUM(T.BASE_AMT)/10000 BASE_AMT ,COUNT(1) NBR
FROM t_loan_s01_syb2 T
GROUP BY T.BHDT_BCH_CDE
ORDER BY 3 DESC


SELECT * FROM rcjc.gl_org G
WHERE 1=1
AND G.OP_ORG_NUM LIKE '%0305%'

-- 蒙商银行巴彦淖尔利民支行
-- 行巴彦淖尔乌拉特前旗支行
-- 商银行巴彦淖尔分行营业部